### ISSUE TITLE
Разработать план управления требованиями (см. описание)

### ISSUE THREAD

**Issue by Yakovlev-Ilya-IT** [sergmin/ngmg#10]
1. Создать в Wiki страничку "План управления требованиями".
2. В плане описать процедуры:
        - создания требования (имеет идентификатор, краткий заголовок и текстовое описание);
        - назначения исполнителя;
        - организация обсуждения и согласования (не принято, принято);
        - назначения статуса (не реализовано, реализовано);
        - связывания тестов и задач с требованиями.

Пример организации процесса управления требованиями см. [здесь](https://ceur-ws.org/Vol-1525/paper-12.pdf).

**Comment by sergmin** [comment]
Статус (Milestone)?

**Comment by Yakovlev-Ilya-IT** [comment]
Вижу что реализованы все пункты, кроме "связывания тестов и задач с требованиями". Хочется узнать когда будет доделана страничка
