### ISSUE TITLE
Выполнить проектирование программы ngmg в части функциональности исполняемого модуля

### ISSUE THREAD

**Issue by sergmin** [sergmin/ngmg#32]
Выполнить проектирование программы ngmg в части функциональности исполняемого модуля. Результат проектирования оформить в разделах [Описания программы](https://github.com/sergmin/ngmg/wiki/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B).

**Comment by Yakovlev-Ilya-IT** [comment]
Статус задачи?

**Comment by sergmin** [comment]
Исполнитель не имеет права закрывать задачу. См. план управления запросами на изменения

**Comment by potapovartyom01** [comment]
С планом управления запросами на изменения ознакомился.
