### ISSUE TITLE
Оформить план документирования

### ISSUE THREAD

**Issue by Yakovlev-Ilya-IT** [sergmin/ngmg#36]
Создать в Wiki страничку "План документирования".
В плане описать:
1. Перечень документов для программы NGMG (выбрать из документов представленных в ГОСТ ЕСТД);
2. Формат документов для предоставления конечному пользователю (pdf, word, html страничка и т.п.);
3. Размещение документов в дистрибутиве NGMG (т.е. где будут находится документы при развертывании программы);
4. Разработка документов
4.1. Размещение исходных документов (где будут находится исходники из которых в последствии будут создавать документы для поставки пользователю)
4.2. Преобразование исходных документов в поставлямые конечному пользователю документы
4.3. Размещение поставляемых документов в репозитории

**Comment by AkulinaLyudmila** [comment]
Добрый вечер, задача выполнена с некоторыми отклонениями от ваших требований.
В частности, названия некоторых заголовков сделала в точности, как указывал преподаватель. 
Спасибо!
