### ISSUE TITLE
Заняться проебразованием комментариев в коде программы NGMG в руководство программиста

### ISSUE THREAD

**Issue by Yakovlev-Ilya-IT** [sergmin/ngmg#39]
1. Для выполнения задачи потребуется предварительно изучить программу doxygen, которая имеет нужный инструментарий
2. Определить вид руководства программиста (pdf, word и т.д.)
3. Определить место размещения руководства программиста на репозитории
4. Заняться преобразованием комментариев в коде программы NGMG в руководство программиста

**Comment by Yakovlev-Ilya-IT** [comment]
Как продвигается задача?

**Comment by AkulinaLyudmila** [comment]
Добрый день! 
Ждём код с комментариями, чтобы преступить к реализации руководства программиста. Шаблон уже готов.

**Comment by AkulinaLyudmila** [comment]
Илья, добрый вечер! Задачу не можем выполнить, так как в программе были неправильно написаны комментарии. 
У нас в программе комментарии выполнены через //, а для программы doxygen необходимо оформить комментарии примерно [так](https://www.doxygen.nl/manual/docblocks.html#cppblock)

**Comment by turkin812** [comment]
Написан шаблон [Руководство программиста](https://github.com/sergmin/ngmg/wiki/%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%81%D1%82%D0%B0) в соответствии [ГОСТу](https://files.stroyinf.ru/Index2/1/4294834/4294834269.htm)
