### ISSUE TITLE
Проебразование комментариев в коде NGMG в руководство программиста

### ISSUE THREAD

**Issue by AkulinaLyudmila** [sergmin/ngmg#43]
1.	Для выполнения задачи потребуется предварительно изучить программу doxygen, которая имеет нужный инструментарий
2.	Определить вид руководства программиста (pdf, word и т.д.)
3.	Определить место размещения руководства программиста на репозитории
4.	Заняться преобразованием комментариев в коде программы NGMG в руководство программиста

**Comment by turkin812** [comment]
Передаю тикет Илье.
Илья, Хай! Для успешной генерации документации на основе doxygen для данного проекта, необходимо наличие кода с подробными комментариями в разрабатываемом ПО. Прошу уведомить о его появлении и местоположении в данном проекте.
Шаблон документации doxygen для примера собрал пока в html файл. Возможности поднять его на доменном имени github нет, т.к. не имею определённых прав у данного проекта.

**Comment by Yakovlev-Ilya-IT** [comment]
Игорь, во первых стоит обсуждать дополнительные вопросы со своим непосредственным руководителем, далее если возникнут проблемы, то решать вопрос мы будем уже с ним.
Во вторых в задаче указано определить вид финальной документации и определить место расположения руководства программиста на репозитории. Эти задачи выполнены?
По поводу комментированного кода - ждём отдел разработки программного обеспечения

**Comment by AkulinaLyudmila** [comment]
Спасибо, задача закрыта!
