### ISSUE TITLE
Создать шаблон спецификации

### ISSUE THREAD

**Issue by AkulinaLyudmila** [sergmin/ngmg#49]
Создать шаблон спецификации [ГОСТ 19.202-78 ](https://www.swrit.ru/doc/espd/19.202-78.pdf)
Добавить в страницу wiki [Спецификация](https://github.com/sergmin/ngmg/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F)

**Comment by turkin812** [comment]
Прошу проверить страницу [Спецификация](https://github.com/sergmin/ngmg/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F)

**Comment by AkulinaLyudmila** [comment]
Задача выполнена, спасибо!
