### ISSUE TITLE
Заняться преобразованием документов

### ISSUE THREAD

**Issue by AkulinaLyudmila** [sergmin/ngmg#51]
Ознакомиться с [План документирования программы NGMG](https://github.com/sergmin/ngmg/wiki/%D0%9F%D0%BB%D0%B0%D0%BD-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F--%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B-NGMG), и в соответствии с пунктом 4 заняться преобразованием соответствующих wiki-страниц в конечные документы.

**Comment by MariamNalchajyan** [comment]
Для конвертирования wiki-страниц(т.е. файлов с расcширеним .md) в pdf-файлы предлагаю использовать утилиту Pandoc. По умолчанию Pandoc создает PDF-файлы с использованием LaTeX. Рекомендуется устанавливать его через MiKTeX.

 Для автоматизации преобразования документов написала [скрипт](https://github.com/sergmin/ngmg/blob/main/Nalchajyan/UpdateDocuments.bat).

**Comment by AkulinaLyudmila** [comment]
Задача выполнена, молодец, спасибо! <3
